# Generated by Django 5.1.3 on 2024-11-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cafe_branch_alter_cafe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
